POST http://localhost:9000/customers HTTP/1.1
content-Type: application/json;

{
  {
    "firstName": "Tran ",
    "lastName":"Tuan",
    "phoneNumber":"0931932039",
    "address":"38 Yen Bai",
    "email": "tuantd@gmail.com",
    "birthday":"2023-3-30"
  }
}